apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: my-dask
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-05-10T16:30:24Z"
  generation: 1
  labels:
    app: dask
    app.kubernetes.io/managed-by: Helm
    chart: dask-2024.1.1
    component: scheduler
    heritage: Helm
    release: my-dask
  name: my-dask-scheduler
  namespace: default
  resourceVersion: "7287"
  uid: 64ee7622-dace-42cc-8e30-ffc44b3dd6e6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: scheduler
      release: my-dask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: scheduler
        release: my-dask
    spec:
      containers:
      - args:
        - dask-scheduler
        - --port=8786
        - --dashboard-address=:8787
        image: us-central1-docker.pkg.dev/my-projectgke/docker-repo/dask/image-processing
        imagePullPolicy: IfNotPresent
        name: my-dask-scheduler
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-10T16:33:19Z"
    lastUpdateTime: "2024-05-10T16:33:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-10T16:30:24Z"
    lastUpdateTime: "2024-05-10T16:33:19Z"
    message: ReplicaSet "my-dask-scheduler-5f778c9c4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
