apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: my-dask
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-05-10T16:30:24Z"
  generation: 1
  labels:
    app: dask
    app.kubernetes.io/managed-by: Helm
    chart: dask-2024.1.1
    component: worker
    heritage: Helm
    release: my-dask
  name: my-dask-worker
  namespace: default
  resourceVersion: "7289"
  uid: a7ffaabe-b54a-4023-a5e3-0deb027788ba
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: worker
      release: my-dask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: worker
        release: my-dask
    spec:
      containers:
      - args:
        - dask-worker
        - my-dask-scheduler:8786
        - --no-dashboard
        - --dashboard-address
        - "8790"
        image: us-central1-docker.pkg.dev/my-projectgke/docker-repo/dask/image-processing
        imagePullPolicy: IfNotPresent
        name: my-dask-worker
        ports:
        - containerPort: 8790
          name: dashboard
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-05-10T16:33:19Z"
    lastUpdateTime: "2024-05-10T16:33:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-10T16:30:24Z"
    lastUpdateTime: "2024-05-10T16:33:19Z"
    message: ReplicaSet "my-dask-worker-64dd4775df" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
