apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-minimal
spec:
  rayVersion: "2.21.0"
  enableInTreeAutoscaling: false  # Disable autoscaling for minimal setup
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - name: ray-head
            image: zyxdenny/ray-mnist:latest
            resources:
              limits:
                cpu: 2  # Adjust CPU limits based on your local machine
                memory: 2Gi  # Adjust memory limits based on your local machine
              requests:
                cpu: 2  # Adjust CPU requests based on your local machine
                memory: 2Gi  # Adjust memory requests based on your local machine
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "ray stop"]
            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 1
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: zyxdenny/ray-mnist:latest
              resources:
                limits:
                  cpu: 1  # Adjust CPU limits based on your local machine
                  memory: 1Gi  # Adjust memory limits based on your local machine
                requests:
                  cpu: 1  # Adjust CPU requests based on your local machine
                  memory: 1Gi  # Adjust memory requests based on your local machine
